/*
* generated by Xtext
*/
package org.lunifera.web.vaadin.designstudy01.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiModel;

/**
 * customization of the default outline structure
 * 
 */
public class Designstudy01OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	/**
	 * Skip the root node.
	 * 
	 * @param parentNode
	 * @param uimodel
	 */
	protected void _createChildren(DocumentRootNode parentNode, UiModel uimodel) {
		createNode(parentNode, uimodel.getTiles());
	}
}
