/*
* generated by Xtext
*/
package org.lunifera.web.vaadin.designstudy01.ui.contentassist;

import org.lunifera.web.vaadin.designstudy01.ui.contentassist.AbstractDesignstudy01ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Designstudy01ProposalProvider extends AbstractDesignstudy01ProposalProvider {

}
