/*
 * generated by Xtext
 */
package org.lunifera.web.vaadin.designstudy01.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.lunifera.web.vaadin.designstudy01.ui.highlighting.Designstudy01HighlightingCalculator;
import org.lunifera.web.vaadin.designstudy01.ui.highlighting.Designstudy01HighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Designstudy01UiModule extends
		org.lunifera.web.vaadin.designstudy01.ui.AbstractDesignstudy01UiModule {
	public Designstudy01UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return Designstudy01HighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return Designstudy01HighlightingCalculator.class;
	}
}
