/*
 * generated by Xtext
 */
package org.lunifera.web.vaadin.designstudy01.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiDetailPart;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiMasterDetailTiles;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiMasterPart;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiTable;
import org.lunifera.web.vaadin.designstudy01.designstudy01.UiTextField;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class Designstudy01LabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public Designstudy01LabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(UiMasterDetailTiles ele) {
		return " Tiles " + ele.getName();
	}

	String text(UiMasterPart ele) {
		return " Master";
	}

	String text(UiDetailPart ele) {
		return " Detail";
	}

	String text(UiTextField ele) {
		return " Text " + ele.getName();
	}

	String text(UiTable ele) {
		return " Table " + ele.getName();
	}
	
	String image(UiMasterDetailTiles ele) {
		return "tiles.png";
	}

	String image(UiMasterPart ele) {
		return "master.png";
	}

	String image(UiDetailPart ele) {
		return "detail.png";
	}

	String image(UiTextField ele) {
		return "textfield.png";
	}

	String image(UiTable ele) {
		return "table.png";
	}
}
