/*
 * generated by Xtext
 */
package org.lunifera.web.vaadin.designstudy01;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Designstudy01RuntimeModule extends org.lunifera.web.vaadin.designstudy01.AbstractDesignstudy01RuntimeModule {

}
